### ISSUE TITLE
Version 0.4 Planning Issue

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#46]
This issue if for planning what features we may want in v0.4.0. __This version will break backwards compatibility__. 

## New Features
This is a list new things that would directly affect the user. 
- [x] Interpolation of profiles and fbm in fidasim.f90: With this we should be able to calculate the bremsstrahlung and npa attenuation without having the beam grid extend past the separatrix along the sightline. It also opens up the door for orbit calculations.
- [x] ```load_plasma```: We lose the ability to handle 3D fields when using interpolation. This switch would allow for users to load up a file that contains the profiles and fields on the beam grid. It would act similar to ```load_neutrals``` switch. 
- [x] Use stored velocity vectors for NBI, DCX, Halo calculation. Also would allow for multiple beams. (Issue #39, #19 , and [discussion](https://github.com/D3DEnergetic/FIDASIM/commit/42f787462a6b8dc43cdddf886748a71c6e2276a4?diff=unified))
- [x] Profile, FBM, Equilibrium, and Tables specification: Users should be able to specify the format of these files so they can be transformed into a form FIDASIM can understand. (Issues #31 #30 #32 #42)
- [x] HDF5 file format: HDF5 has better features and language support. If we are going to break backwards compatibility we might as well destroy it. (Issue #15 #44)
- [x] Improved Documentation: This just needs to be done. 
- [x] Apertures for NPA and NBI (Issue #50)
- [x] Dump halo generations (Issue #56)

## Interface Routine Improvements
These are things that improve how FIDASIM would interact with other software/databases.
- [x] EFIT/GEQDSK Tools: Ben has improved the current routines. Related to Issue #30 
- [x] TRANSP Tools: We have some tools to extract all the information needed for FIDASIM to run (beam geometry, profiles, equilibrium, fbm) but they need to be streamlined. Related to Issue #32 and #21 
- [x] FBM Tools: We need routines that can read distributions produced by other codes into a format FIDASIM can understand. Related to Issue #32
- [x] Table Tools: We need routines to make tables for other tables from other databases i.e. ADAS, PREACT, ... Related to #42 

## Maintenance
Bug fixes and things users wont notice. 
- [x] Resolve differences in core analysis routines (Issue #41)
- [x] Tables in new format: It is sometimes necessary to inspect the tables. The current .bin forms is a hindrance in that endeavour. (Issue #44)
- [x] Beam grid and rotations: fidasim.f90 uses the wrong coordinate system (-x into plasma, instead of +x ) because of this the angles  ```alpha``` and ```beta``` variables in the prefida input file are not intuitive. Tilted beams are also broken. (Issue #43)
- [x] Right now prefida checks the inputs to make sure they are valid. With the upcoming changes it would be prudent to do the same for the device routines outputs (Issue #36) 

Comments?
@bgrierson21 @geigerb

**Comment by bgrierson21** [comment]
What is the current capability for inclusion of other ions?  In the past, I've used the 3D grid and rates from ADAS to calculate the carbon brightness along the spectroscopic sightlines to cross-verify the carbon density calculation between FIDASIM and the DIII-D impurity density calculator.  Will this be an issue for the grids of the new version?  If the new version has a different gridding then this may not be possible, and we'd have to add the impurity charge-excahge radiation as a FIDASIM feature.

**Comment by lstagner** [comment]
The current version of FIDASIM maps everything(fields,sightlines,profiles,neutrals) onto the beam grid. With the new version you would have two grids, the beam grid and the interpolation grid. The beam grid(X,Y,Z) is the same grid that the current version has except it will only contain the neutrals and the sightlines. The interpolation grid (R,W) will have the have the magnetic field/flux coordinates mapped onto it so we can then interpolate the plasma parameters. The ```load_plasma``` switch I suggested will allow the user to load a file that has everything mapped onto the beam grid. With this switch enabled the new version of FIDASIM will act like the current version. So anything you can do with the current version you should be able to do with the new version. At least in regards to the grid. 

In regards to calculating the impurity cx spectra I will defer to Ben (@geigerb ) since he is more familiar with the atomic physics portion of FIDASIM. It would certainly be a nice feature to have.

**Comment by lstagner** [comment]
Done in #64
